data:
  labels: ["Lung Opacity", "Cardiomegaly", "Pleural thickening", "Aortic enlargement", "Pleural effusion", "Pulmonary fibrosis", "Tuberculosis", "No finding"]
  batch_size: 16
  num_workers: 8
optim:
  epochs: 500
  weight_decay_end: 0.2
  base_lr: 1e-04  
  lr_scheduler: True
  weight_decay: 0.05
  warmup_epochs: 80
  layerwise_decay: 1.0
  