VinDr-CXR:
  data_root_folder: "/hpcwork/rwth1833/datasets/preprocessed/VinDr-CXR"
  num_workers: 8

CANDID-PTX:
  data_root_folder: "/hpcwork/rwth1833/datasets/preprocessed/CANDID-PTX"
  num_workers: 8

RSNA-Pneumonia:
  data_root_folder: "/hpcwork/rwth1833/datasets/preprocessed/RSNA-Pneumonia"
  num_workers: 8

VinDr-Mammo:
  data_root_folder: "/hpcwork/rwth1833/datasets/preprocessed/VinDr-Mammo/birads/single_view"
  num_workers: 8
  multi_view:
    num_views: 4
    view_fusion_type: "mean"
    adapter_dim: null
    view_fusion_hidden_dim: null
    data_root_folder_multi_view: "/hpcwork/rwth1833/datasets/preprocessed/VinDr-Mammo/birads/multi_view"
