VinDr-CXR:
  data_root_folder: "/hpcwork/rwth1833/datasets/VinDr-CXR/download/physionet.org/files/vindr-cxr/1.0.0"
  class_labels: ["Lung Opacity", "Cardiomegaly", "Pleural thickening", "Aortic enlargement", "Pleural effusion", "Pulmonary fibrosis", "Tuberculosis", "No finding"]
  num_workers: 8

CANDID-PTX:


RSNA-Pneumonia:


VinDr-Mammography:
