VinDr-CXR:
  data_root_folder: "/hpcwork/rwth1833/datasets/VinDr-CXR/download/physionet.org/files/vindr-cxr/1.0.0"
  num_workers: 8
  class_labels: ["Lung Opacity", "Cardiomegaly", "Pleural thickening", "Aortic enlargement", "Pleural effusion", "Pulmonary fibrosis", "Tuberculosis", "No finding"]

CANDID-PTX:
  data_root_folder: "/hpcwork/rwth1833/datasets/CANDID-PTX"
  num_workers: 8

RSNA-Pneumonia:
  data_root_folder: "/hpcwork/rwth1833/datasets/RSNA-Pneumonia"
  num_workers: 8

VinDr-Mammography:
  data_root_folder: "/hpcwork/rwth1833/datasets/VinDr-Mammography"
  num_workers: 8
