VinDr-CXR:
  data_root_folder: "/mnt/ocean_storage/users/cchang/VinDr-CXR"
  num_workers: 4

RSNA-Pneumonia:
  data_root_folder: "/hpcwork/rwth1833/datasets/preprocessed/RSNA-Pneumonia"
  num_workers: 16

VinDr-Mammo:
  data_root_folder: "/mnt/ocean_storage/users/cchang/birads/single_view"
  num_workers: 4 
  multi_view:
    num_views: 4
    view_fusion_type: "mean"
    adapter_dim: null
    view_fusion_hidden_dim: null
    data_root_folder_multi_view: "/mnt/ocean_storage/users/cchang/birads/multi_view"

TAIX-Ray:
  data_root_folder: "/mnt/ocean_storage/users/cchang/TAIX-Ray"
  num_workers: 4

NODE21:
  data_root_folder: "/hpcwork/rwth1833/datasets/preprocessed/NODE21"
  num_workers: 4

COVID-CXR:
  data_root_folder: "/hpcwork/rwth1833/datasets/preprocessed/COVID-CXR"
  num_workers: 4

VinDr-PCXR:
  data_root_folder: "/mnt/ocean_storage/users/cchang/preprocessed_data/VinDr-PCXR"
  num_workers: 4

VinDr-SpineXR:
  data_root_folder: "/mnt/ocean_storage/users/cchang/preprocessed_data/VinDr-SpineXR"
  num_workers: 4